_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.11.0rc1
        t:
            "1":
                - 1
                - 41
                - 49
                - 51
                - 55
                - 63
            "2":
                - 1
                - 41
                - 49
                - 51
                - 55
                - 63
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.0rc1
            "5": 0.19.9
            "8":
                - 5
                - 9
            "12": 0.19.9
            "13": linux-x86_64
batch_size:
    value: 14
batches_per_epoch:
    value: 1
embedding_dim:
    value: 1024
epochs:
    value: 10
flow_field_fourier_features:
    value: 128
flow_field_hidden_dim:
    value: 512
gamma:
    value: 0.999
idx_path:
    value: ../idx/validation
lr:
    value: 0.001
motion_encoder_hidden_dim:
    value: 512
motion_encoder_seq_len:
    value: 11
road_map_image_size:
    value: 224
tfrecord_path:
    value: ../data1/waymo_dataset/uncompressed/tf_example/validation
token_dim:
    value: 768
trajectory_feature_dim:
    value: 10
weight_decay:
    value: 0
